/**
 * wasmsh TypeScript Example
 *
 * Demonstrates using the wasmsh shell from Node.js via wasm-pack.
 *
 * Prerequisites:
 *   cd ../.. && wasm-pack build crates/wasmsh-browser --target nodejs --release --out-dir ../../pkg/nodejs
 *   cd examples/typescript && npm install
 *
 * Run:
 *   npx tsx example.ts
 */

// @ts-ignore -- generated by wasm-pack, types may not exist until built
import { WasmShell } from "wasmsh-browser";

// -- Helpers --

interface StdoutEvent { Stdout: number[] }
interface StderrEvent { Stderr: number[] }
interface ExitEvent { Exit: number }
interface VersionEvent { Version: string }
interface DiagnosticEvent { Diagnostic: [string, string] }

type ShellEvent =
  | StdoutEvent
  | StderrEvent
  | ExitEvent
  | VersionEvent
  | DiagnosticEvent;

function parseEvents(json: string): ShellEvent[] {
  return JSON.parse(json);
}

function getStdout(events: ShellEvent[]): string {
  const bytes: number[] = [];
  for (const evt of events) {
    if ("Stdout" in evt) bytes.push(...evt.Stdout);
  }
  return new TextDecoder().decode(new Uint8Array(bytes));
}

function getStderr(events: ShellEvent[]): string {
  const bytes: number[] = [];
  for (const evt of events) {
    if ("Stderr" in evt) bytes.push(...evt.Stderr);
  }
  return new TextDecoder().decode(new Uint8Array(bytes));
}

function getExitCode(events: ShellEvent[]): number {
  for (const evt of events) {
    if ("Exit" in evt) return evt.Exit;
  }
  return -1;
}

function run(shell: WasmShell, cmd: string) {
  const events = parseEvents(shell.exec(cmd));
  return {
    stdout: getStdout(events),
    stderr: getStderr(events),
    exitCode: getExitCode(events),
  };
}

// -- Main --

function main() {
  const shell = new WasmShell();

  // Initialize with step budget (0 = unlimited)
  const initEvents = parseEvents(shell.init(BigInt(0), "[]"));
  const version = initEvents.find((e): e is VersionEvent => "Version" in e);
  console.log("wasmsh protocol version:", version?.Version);
  console.log("");

  // 1. Basic command
  console.log("=== 1. Basic Commands ===");
  console.log(run(shell, "echo 'Hello from wasmsh!'").stdout.trimEnd());
  console.log(run(shell, "echo one; echo two; echo three").stdout.trimEnd());
  console.log("");

  // 2. Pipelines
  console.log("=== 2. Pipelines ===");
  console.log(
    run(shell, "echo 'banana apple cherry' | tr ' ' '\n' | sort").stdout.trimEnd()
  );
  console.log("");

  // 3. Variables and parameter expansion
  console.log("=== 3. Variables & Expansion ===");
  run(shell, 'NAME="World"');
  console.log(run(shell, 'echo "Hello, ${NAME}!"').stdout.trimEnd());
  console.log(
    run(shell, 'FILE="/path/to/report.tar.gz"; echo "${FILE##*/}"').stdout.trimEnd()
  );
  console.log("");

  // 4. Arrays
  console.log("=== 4. Arrays ===");
  run(shell, "fruits=(apple banana cherry mango)");
  console.log(run(shell, 'echo "count: ${#fruits[@]}"').stdout.trimEnd());
  console.log(
    run(shell, 'for f in "${fruits[@]}"; do echo "  - $f"; done').stdout.trimEnd()
  );
  console.log("");

  // 5. Arithmetic
  console.log("=== 5. Arithmetic ===");
  const fib = run(
    shell,
    "a=0; b=1; for ((i=0; i<10; i++)); do echo -n \"$a \"; ((tmp=a+b, a=b, b=tmp)); done; echo"
  );
  console.log("Fibonacci:", fib.stdout.trimEnd());
  console.log("Bitwise:", run(shell, "echo $(( 0xFF & 0x0F )) $(( 1 << 8 ))").stdout.trimEnd());
  console.log("");

  // 6. Virtual filesystem
  console.log("=== 6. Virtual Filesystem ===");
  shell.write_file(
    "/data/config.toml",
    new TextEncoder().encode('[server]\nhost = "localhost"\nport = 8080\n')
  );
  console.log(run(shell, "cat /data/config.toml").stdout.trimEnd());
  run(shell, "mkdir -p /data/logs");
  run(shell, 'echo "2024-01-01 INFO started" > /data/logs/app.log');
  run(shell, 'echo "2024-01-02 ERROR failed" >> /data/logs/app.log');
  console.log("Grep:", run(shell, "grep ERROR /data/logs/app.log").stdout.trimEnd());
  console.log("");

  // 7. Functions and control flow
  console.log("=== 7. Functions ===");
  run(
    shell,
    'factorial() { local n=$1; if (( n <= 1 )); then echo 1; else local sub=$(factorial $((n-1))); echo $((n * sub)); fi; }'
  );
  console.log("10! =", run(shell, "echo $(factorial 10)").stdout.trimEnd());
  console.log("");

  // 8. Extended test [[ ]]
  console.log("=== 8. Extended Test [[ ]] ===");
  console.log(
    run(
      shell,
      'file="report.csv"; if [[ $file == *.csv ]]; then echo "$file is CSV"; fi'
    ).stdout.trimEnd()
  );
  console.log("");

  // 9. Error handling
  console.log("=== 9. Error Handling ===");
  const err = run(shell, "nonexistent_command 2>&1");
  console.log("Exit code:", err.exitCode);
  console.log("");

  // 10. Utilities
  console.log("=== 10. Utilities ===");
  shell.write_file("/data/hello.txt", new TextEncoder().encode("hello\n"));
  console.log("MD5:", run(shell, "md5sum /data/hello.txt").stdout.trimEnd());
  console.log("Base64:", run(shell, 'echo -n "wasmsh" | base64').stdout.trimEnd());
  console.log("");

  console.log("All examples completed successfully!");
}

main();
